USE DATABASE FLUX_DB;
USE WAREHOUSE FLUX_WH;
USE SCHEMA APPLICATIONS;

CREATE STAGE IF NOT EXISTS UTILITY_PDF_INTERNAL_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Phase 3a internal validation stage for utility PDF corpus (drop after Phase 3a passes)';

-- Verify
SHOW STAGES LIKE 'UTILITY_PDF_INTERNAL_STAGE' IN SCHEMA FLUX_DB.APPLICATIONS;
